### ISSUE TITLE
Android App crashed after tap on style 

### ISSUE THREAD

**Issue by n00ner** [AnetaTexler/FaceBlit#6]
I put model into downloads but got these crashes 

First crash

2021-04-28 15:33:33.189 24926-26079/texler.faceblit A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 26079 (pool-3-thread-1), pid 24926 (texler.faceblit)

Second crash 

 Process: texler.faceblit, PID: 27296
    java.lang.OutOfMemoryError: Failed to allocate a 67108880 byte allocation with 25165824 free bytes and 57MB until OOM, target footprint 166366248, growth limit 201326592
        at java.util.Arrays.copyOf(Arrays.java:3161)
        at java.io.ByteArrayOutputStream.toByteArray(ByteArrayOutputStream.java:191)
        at texler.faceblit.utils.ResourceHelper.getCubeFromResource(ResourceHelper.java:176)
        at texler.faceblit.fragments.StyleSelectorFragment.setStyleData(StyleSelectorFragment.java:73)
        at texler.faceblit.RecyclerViewAdapter$1.onClick(RecyclerViewAdapter.java:63)
        at android.view.View.performClick(View.java:8160)
        at android.view.View.performClickInternal(View.java:8137)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30250)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
        
Device: Samsung A51

**Comment by n00ner** [comment]
Try to decrease num of Bitmap allocations

**Comment by AnetaTexler** [comment]
Hi!
I tested it on Samsung A50 (4GB RAM) with no such error. From the log I can see it happens when the lookup table (~65MB) is loaded from resources. You can try to request a larger heap size by adding `android:largeHeap="true"` on the `<application>` element in the manifest. Please, let me know if it helps.
